### ISSUE TITLE
Memory overloaded when training model

### ISSUE THREAD

**Issue by suonbo** [MLSTRUCT/MLSTRUCT-FP_benchmarks#3]
Hi, I have trained the model on a 24GB RAM machine. I monitor the memory allocation while training and see that the memory% was increasing by the time until loaded 100% and then my machine crashes.
I have config the model to train only on batch size 1. So where does the issue come from? How should I resolve this issue?

![image](https://github.com/MLSTRUCT/MLSTRUCT-FP_benchmarks/assets/87938340/043794d5-1e4a-4a6b-bf8c-852bd9b813e5)

**Comment by ppizarror** [comment]
Hi, @suonbo. It is probably because the data loader loads the entire dataset, and depending on how you assemble the image patches (for example, if you create 512x512px), it might consume a lot of memory. For such issues:

1. Update the DataFloorPhoto class, placing a limit on how many images you are loading on memory. https://github.com/MLSTRUCT/MLSTRUCT-FP_benchmarks/blob/832af2a4c178766b9d50a8cf8c89f2f17f238009/MLStructFP_benchmarks/ml/model/core/_data_floor_photo.py#L190-L200
2. You also might update the training method, limiting how many parts (each part is a processed batch of patches from a given floor) are loaded. You can randomize it too. https://github.com/MLSTRUCT/MLSTRUCT-FP_benchmarks/blob/832af2a4c178766b9d50a8cf8c89f2f17f238009/MLStructFP_benchmarks/ml/model/architectures/_fp_unet.py#L111-L125
3. Decrease the number of plans when assembling your dataset. Also, reducing the image size (to maybe 256x256) is a good idea. If you increase also crop size it will generate less images per floor.

**Comment by suonbo** [comment]
> Hi, @suonbo. It is probably because the data loader loads the entire dataset, and depending on how you assemble the image patches (for example, if you create 512x512px), it might consume a lot of memory. For such issues:
> 
> 1. Update the DataFloorPhoto class, placing a limit on how many images you are loading on memory. https://github.com/MLSTRUCT/MLSTRUCT-FP_benchmarks/blob/832af2a4c178766b9d50a8cf8c89f2f17f238009/MLStructFP_benchmarks/ml/model/core/_data_floor_photo.py#L190-L200
> 2. You also might update the training method, limiting how many parts (each part is a processed batch of patches from a given floor) are loaded. You can randomize it too. https://github.com/MLSTRUCT/MLSTRUCT-FP_benchmarks/blob/832af2a4c178766b9d50a8cf8c89f2f17f238009/MLStructFP_benchmarks/ml/model/architectures/_fp_unet.py#L111-L125
> 3. Decrease the number of plans when assembling your dataset. Also, reducing the image size (to maybe 256x256) is a good idea. If you increase also crop size it will generate less images per floor.

Thank you for your suggestion!
